### ISSUE TITLE
MQTT Errors and eventually process dies.

### ISSUE THREAD

**Issue by larizzo** [TD22057/insteon-mqtt#10] opened 2017-12-12 21:17 UTC
I don't know if this is something with my setup but the insteon-mqtt keeps dying and this is what's in the log.

```

2017-12-12 15:17:26 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
2017-12-12 15:17:51 INFO Mqtt: MQTT device opened 10.0.0.11 1883
2017-12-12 15:18:58 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
2017-12-12 15:21:16 ERROR Mqtt: MQTT connection error to 10.0.0.11 1883
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/network/Mqtt.py", line 188, in connect
    self.client.connect(self.host, self.port, keepalive=60)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 768, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 895, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
2017-12-12 15:21:25 INFO Mqtt: MQTT device opened 10.0.0.11 1883
2017-12-12 15:22:31 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
2017-12-12 15:22:41 INFO Mqtt: MQTT device opened 10.0.0.11 1883
2017-12-12 15:23:48 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
2017-12-12 15:23:58 INFO Mqtt: MQTT device opened 10.0.0.11 1883
2017-12-12 15:25:05 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
2017-12-12 15:25:15 INFO Mqtt: MQTT device opened 10.0.0.11 1883
2017-12-12 15:26:21 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
2017-12-12 15:26:31 INFO Mqtt: MQTT device opened 10.0.0.11 1883
2017-12-12 15:27:38 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
2017-12-12 15:27:48 INFO Mqtt: MQTT device opened 10.0.0.11 1883
2017-12-12 15:28:55 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
2017-12-12 15:29:37 INFO Mqtt: MQTT device opened 10.0.0.11 1883
2017-12-12 15:31:37 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
2017-12-12 15:31:37 INFO Mqtt: MQTT disconnection 10.0.0.11 1883
```

**Comment by larizzo** [comment] 2017-12-12 21:23
On my mosquitto server is see:

`Socket error on client insteon-mqtt, disconnecting.`

**Comment by TD22057** [comment] 2017-12-12 21:26
1. Check your keep alive in the broker.  The broker will kill the connection if it doesn't see traffic for a certain amount of time.  The client sends a packet every N seconds to insure that doesn't happen but if the broker setting is shorter (or equal) to that time, it will drop connection a lot.  N is currently hard coded in Mqtt.py line 154 at 60 seconds.  It looks like the broker might have that set as the keep alive time as well which would cause this.  I'll change it to be a setting but until then you can either edit broker and restart it or edit the line yourself and try that.  I usually try and keep the client keep alive at 1/2 the server setting.  

2. I'd strongly recommend that you use the virtual env system.  Installing in the system directory will cause problems sooner or later.  For example, there was a bug in paho.mqtt a little while ago.  If you install in a virtualenv, you can be sure to update that to get the latest version.  If you install in the system dir, there is a good chance you can't get the latest version or it might conflict with other dependencies that the system tools have. (speaking from experience here - happened several times to me until I switched to using virtual envs for installs).

**Comment by TD22057** [comment] 2017-12-12 21:47
I submitted an update on the dev branch to allow a keep alive input time in the config.yaml file.  Turns out the default server time is 60 seconds so maybe that's what the problem is (I updated the default to 30 sec).  FYI I haven't been able to reproduce this at all and using paho.mqtt version 1.3.1 and mosquitto version 1.4.14.

**Comment by TD22057** [comment] 2017-12-12 21:57
Also - check your paho.mqtt version to make sure it's the latest and mosquitto.  There was a [bug in mosquitto](https://github.com/eclipse/mosquitto/issues/419) that caused this behavior as well.

I added another update on the dev branch.  If you set logging level to be 5, it will turn on the MQTT client level debugging.  As an example, I have keep_alive set to 30 and I see this so I know the keep alive packets are getting sent and responded to.
```
...
2017-12-12 13:55:41 Level 5 Mqtt: Sending PINGREQ
2017-12-12 13:55:41 Level 5 Mqtt: Received PINGRESP
2017-12-12 13:56:11 Level 5 Mqtt: Sending PINGREQ
2017-12-12 13:56:11 Level 5 Mqtt: Received PINGRESP
...
```

**Comment by larizzo** [comment] 2017-12-12 23:17
Thanks for the help! I'll give this a test and let you know. BTW I'm using a container that's why I haven't bothered to setup the virtualenv since I blow out my container every time I upgrade insteon-mqtt.

**Comment by larizzo** [comment] 2017-12-13 02:06
So far looks good, I'll let you know tomorrow.

**Comment by larizzo** [comment] 2017-12-13 20:54
Still looks good! Thanks. So what do you think about splitting the device configuration and the MQTT stuff at the bottom or some other combination of that into multiple config files. The reason I ask is that I had to move over my configuration 3 times in the last 3 days (testing the MQTT keep_alive, then the extra logging and now to test the keylinc).

I can't think of a great way to spread it into multiple files though... Devices for sure would be nice to have separate.

**Comment by TD22057** [comment] 2017-12-13 22:40
Good.  I'm going to close this and we can discuss the include option in issue #11.

**Closed by TD22057** 2017-12-13 22:40 UTC
