### ISSUE TITLE
Error message: scene() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by MrGibbage** [TD22057/insteon-mqtt#336] opened 2021-01-26 13:20 UTC
Getting an error message, however, everything still works as expected. Thought you might want to know.
```
2021-01-26 08:00:43 INFO Mqtt: MQTT message insteon/command/modem b'{"cmd":"scene","name":"garage","is_on":1}'
2021-01-26 08:00:43 UI Mqtt: Commanding Modem device 53.c1.0e (modem) cmd=scene
2021-01-26 08:00:43 INFO Modem: Modem scene 21 on=on
2021-01-26 08:00:43 INFO Protocol: Write message to modem: Modem Scene: grp: 21 cmd: 0x11 0x00
2021-01-26 08:00:43 DEBUG Protocol: Write bytes to modem: 0261151100
2021-01-26 08:00:43 DEBUG Serial: Wrote 5 bytes to serial /dev/ttyUSB0
2021-01-26 08:00:43 INFO Protocol: Read 0x61: Modem Scene: grp: 21 cmd: 0x11 0x00 ack: True
2021-01-26 08:00:43 DEBUG Protocol: Passing msg to write handler: ModemScene handler
2021-01-26 08:00:45 INFO Mqtt: MQTT message insteon/command/3c.31.e8 b'{"cmd":"scene","name":"garage","is_on":1}'
2021-01-26 08:00:45 UI Mqtt: Commanding switch device 3c.31.e8 (garage) cmd=scene
2021-01-26 08:00:45 ERROR Mqtt: Error running command scene on device 3c.31.e8 (garage)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/insteon_mqtt/mqtt/Mqtt.py", line 280, in handle_cmd
    cmd_func(on_done=on_done, **data)
TypeError: scene() got an unexpected keyword argument 'name'
2021-01-26 08:00:45 INFO Protocol: Read 0x58: All link status ack: 1
2021-01-26 08:00:45 DEBUG Protocol: Passing msg to write handler: ModemScene handler
2021-01-26 08:00:45 DEBUG ModemScene: Modem scene 21 command ACK
2021-01-26 08:00:45 DEBUG Modem: Found 1 responders in group 21
2021-01-26 08:00:45 DEBUG Modem: Group 21 -> ['3c.31.e8']
2021-01-26 08:00:45 INFO Modem: 53.c1.0e (modem) broadcast to 3c.31.e8 for group 21
2021-01-26 08:00:45 INFO Switch: Setting device 3c.31.e8 (garage) on True normal scene
2021-01-26 08:00:45 INFO Switch: MQTT received on/off 3c.31.e8 (garage) on: True normal 'scene'
2021-01-26 08:00:45 DEBUG Mqtt: MQTT publish insteon/3c.31.e8/state ON qos=1 ret=1
2021-01-26 08:00:45 UI Mqtt: Scene command complete
2021-01-26 08:00:45 DEBUG Protocol: Write handler finished
2021-01-26 08:00:45 INFO Protocol: Read 0x50: Std: 3c.31.e8 Type.CLEANUP_ACK grp: 15 cmd: 11 15
2021-01-26 08:00:45 DEBUG Protocol: Setting next write time: 1611666046.029609
2021-01-26 08:00:45 DEBUG MsgHistory: Received 0 hops, total 1 for 11 entries
2021-01-26 08:00:45 WARNING Protocol: No read handler found for message type 0x50: Std: 3c.31.e8 Type.CLEANUP_ACK grp: 15 cmd: 11 15
2021-01-26 08:00:45 DEBUG Mqtt: MQTT writing
```

**Comment by krkeegan** [comment] 2021-01-26 17:27
Pretty sure this was fixed in 0.7.6, are you sure you are up to date?

**Comment by krkeegan** [comment] 2021-01-26 17:57
Sorry, that last comment is wrong.  The problem is that only modem scenes accept the name attribute.  Devices scenes do not have names.  See the documentation [here](https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#scene-triggering).

**Comment by MrGibbage** [comment] 2021-01-26 21:09
I did send that command to `insteon/command/modem`. The scene is set up where only the modem is the controller.

But I did just notice that I am on 0.7.4. I am on hass-os and I think I have to do something special to get insteon-mqtt updated. I don't remember those steps though.

**Comment by krkeegan** [comment] 2021-01-26 22:02
hmm, no the actual issue occurs on a command not sent to the modem, maybe check your automations?  specifically it went to `insteon/command/3c.31.e8`

```
2021-01-26 08:00:45 INFO Mqtt: MQTT message insteon/command/3c.31.e8 b'{"cmd":"scene","name":"garage","is_on":1}'
2021-01-26 08:00:45 UI Mqtt: Commanding switch device 3c.31.e8 (garage) cmd=scene
2021-01-26 08:00:45 ERROR Mqtt: Error running command scene on device 3c.31.e8 (garage)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/insteon_mqtt/mqtt/Mqtt.py", line 280, in handle_cmd
    cmd_func(on_done=on_done, **data)
TypeError: scene() got an unexpected keyword argument 'name'
```

**Comment by MrGibbage** [comment] 2021-01-26 22:44
Ahhh!!! That's is. It was in the automation. :) I owe you a beer. Next round is on me.

**Closed** 2021-01-26 23:03 UTC
