### ISSUE TITLE
Device off after scene command not working

### ISSUE THREAD

**Issue by j3kestrel** [TD22057/insteon-mqtt#36] opened 2018-02-11 23:05 UTC
I haven't yet figured out why, but the mechanism to turn the targeted device off after scene broadcast is ACK'ed is not working.  The broadcast ACK is apparently not received.  The closest I see is `Switch: Switch 15.3d.3d broadcast OFF grp: 1`.  The log below is for a switch.  With the pull-request #35 applied, I get the same result with a KeypadLinc Switch (not Dimmer).

```
2018-02-11 17:19:23 DEBUG Switch: Switch message insteon/15.3d.3d/scene b'OFF'
2018-02-11 17:19:23 DEBUG MsgTemplate: Input template render: '{ "cmd" : "off" }'
2018-02-11 17:19:23 INFO Switch: Switch input command: {'cmd': 'off'}
2018-02-11 17:19:23 INFO Switch: Switch 15.3d.3d scene off
2018-02-11 17:19:23 INFO Protocol: Write to modem: Ext: 15.3d.3d, Type.DIRECT ext, 30 00  01 00 00 13 00 00 00 00 00 00 00 00 00 00 
2018-02-11 17:19:23 DEBUG Protocol: Write to modem: 02 62 15 3d 3d 1f 30 00 01 00 00 13 00 00 00 00 00 00 00 00 00 bc
2018-02-11 17:19:23 DEBUG Serial: Wrote 22 bytes to serial /dev/ttyUSB0
2018-02-11 17:19:23 INFO Protocol: Read 0x62: Ext: 15.3d.3d, Type.DIRECT ext, 30 00 ack: True 01 00 00 13 00 00 00 00 00 00 00 00 00 bc 
2018-02-11 17:19:23 DEBUG Protocol: Passing msg to write handler
2018-02-11 17:19:23 DEBUG StandardCmd: 15.3d.3d got msg ACK
2018-02-11 17:19:24 INFO Protocol: Read 0x50: Std: 15.3d.3d->49.f7.37 Type.DIRECT_ACK cmd: 30 00
2018-02-11 17:19:24 DEBUG Protocol: Passing msg to write handler
2018-02-11 17:19:24 DEBUG Switch: Switch 15.3d.3d ACK: Std: 15.3d.3d->49.f7.37 Type.DIRECT_ACK cmd: 30 00
2018-02-11 17:19:24 DEBUG Protocol: Write handler finished
2018-02-11 17:19:24 INFO Protocol: Read 0x50: Std: 15.3d.3d Type.ALL_LINK_BROADCAST grp: 01 cmd: 13 00
2018-02-11 17:19:24 INFO Broadcast: Handling all link broadcast for 15.3d.3d 'gr_couch'
2018-02-11 17:19:24 INFO Switch: Switch 15.3d.3d broadcast OFF grp: 1
2018-02-11 17:19:24 DEBUG Base: Found 3 responders in group 1
2018-02-11 17:19:24 DEBUG Base: Group 1 -> ['49.f7.37', '15.62.9d', '43.6b.a2']
2018-02-11 17:19:24 INFO Base: 15.3d.3d (gr_couch) broadcast to 49.f7.37 for group 1
2018-02-11 17:19:24 INFO Base: 15.3d.3d (gr_couch) broadcast to 15.62.9d for group 1
2018-02-11 17:19:24 INFO Dimmer: Setting device 15.62.9d (gr_north_valance) on=0
2018-02-11 17:19:24 INFO Dimmer: MQTT received level change 15.62.9d (gr_north_valance) = 0
2018-02-11 17:19:24 DEBUG Mqtt: MQTT publish insteon/15.62.9d/state { "state" : "OFF", "brightness" : 0 } qos=1 ret=1
2018-02-11 17:19:24 WARNING Base: 15.3d.3d (gr_couch) broadcast - device 43.6b.a2 not found
2018-02-11 17:19:24 DEBUG Mqtt: MQTT writing
2018-02-11 17:19:27 INFO Protocol: Read 0x50: Std: 15.3d.3d Type.ALL_LINK_CLEANUP grp: 01 cmd: 13 01
```

**Comment by j3kestrel** [comment] 2018-02-11 23:09
Device `43.6b.a2` that is not found is an older serial PLM that is not presently in service.

I don't understand why `15.62.9d` responds the way it does.  It is a KeypadLinc Switch that has one of its scene buttons paired to the switch who's scene I am commanding.  It is apparently responding with the state of its built-in switch.  There may be multiple or confusing issues there as the response is always `{ "state" : "OFF", "brightness" : 0 }` even when it is on.  I suspect some topic confusion?

I believe there are a number of issues with scenes that will need to get fixed one at a time.

**Comment by TD22057** [comment] 2018-02-15 04:14
Let me see if I understand you here - you have 15.3d.3d which is a switch (what's the model number?).  And it's group 1 scene is linked to 3 devices:
- 49.f7.37  (I assume this is the PLM modem?)
- 15.62.9d  (looks like a dimmer)
- 43.6b.a2  (not active modem)

You send a scene simulation command to 15.3d.3d for group 1.  That correctly triggers a group 1, cmd 13 all link broadcast from that device.  What happens with each device?

Note that the MQTT messages you see for 15.62.9d is nor from that device.  It's read from the all link database that the software has for that device.  Devices do not broadcast a state change when they respond to scene command.  The only way to get their actual state is to poll them all (with some delay) or to assume that the network is healthy and assume they did the right thing which is dictated by the database.  So the code just looks up the value the device will take on from the database and sends that out in the MQTT message.

What do the 15.62.9d and 15.3d.3d all link database look like (try the print-db command using the command line tool for each of them)?

I'll run some more tests on my devices to see what the logs look like for the scene commands.  I know they were pretty finicky to get it to work properly (like the broadcast_done pseudo-hack).

**Comment by TD22057** [comment] 2018-02-15 04:38
FYI - I ran tests w/ 2 dimmer KeypadLinc's with scenes on the dimmer (grp 1) and non-dimmer (grp 3) buttons.  I used the command line tool to send a scene command for on and off to both and they both worked as they should.  They run the command and this is what I see at the end:
```
...
INFO Protocol: Read 0x50: Std: 46.7b.bc Type.ALL_LINK_CLEANUP grp: 01 cmd: 13 01
INFO Protocol: Read 0x50: Std: 46.7b.bc Type.ALL_LINK_BROADCAST grp: 01 cmd: 06 00
...
```

Which of course is the broadcast ACK message (cmd 0x06) that the broadcast_done callback needs to use in the off command to trip the device.  My KeypadLinc is fairly new so maybe older devices don't do this?  It might also be possible to use the broadcast clean up as the trigger but I'd need to run some tests to see if that works (sending the manual off too early interrupted the broadcast messages and stopped the scene response in some devices).

**Comment by TD22057** [comment] 2018-02-15 04:51
Another thing you can try is to click one of the keypadlinc buttons. Here's what I see when I click button 3:
```
2018-02-14 20:50:09 INFO Protocol: Read 0x50: Std: 46.7b.bc Type.ALL_LINK_BROADCAST grp: 03 cmd: 11 00
2018-02-14 20:50:09 INFO Broadcast: Handling all link broadcast for 46.7b.bc 'kp1'
2018-02-14 20:50:09 INFO KeypadLinc: KeypadLinc 46.7b.bc broadcast ON grp: 3
2018-02-14 20:50:09 INFO KeypadLinc: MQTT received button press 46.7b.bc (kp1) = btn 3 on True
2018-02-14 20:50:09 DEBUG Mqtt: MQTT publish insteon/46.7b.bc/state/3 ON qos=1 ret=1
2018-02-14 20:50:09 DEBUG Base: Found 2 responders in group 3
2018-02-14 20:50:09 DEBUG Base: Group 3 -> ['44.85.11', '3c.42.9b']
2018-02-14 20:50:09 INFO Base: 46.7b.bc (kp1) broadcast to 44.85.11 for group 3
2018-02-14 20:50:09 INFO Base: 46.7b.bc (kp1) broadcast to 3c.42.9b for group 3
2018-02-14 20:50:09 DEBUG Mqtt: MQTT writing
2018-02-14 20:50:10 INFO Protocol: Read 0x50: Std: 46.7b.bc Type.ALL_LINK_CLEANUP grp: 03 cmd: 11 03
2018-02-14 20:50:10 INFO Protocol: Read 0x50: Std: 46.7b.bc Type.ALL_LINK_BROADCAST grp: 03 cmd: 06 00
2018-02-14 20:50:10 INFO Broadcast: Handling all link broadcast for 46.7b.bc 'kp1'
2018-02-14 20:50:10 INFO KeypadLinc: KeypadLinc 46.7b.bc broadcast ACK grp: 3
```

Do you get the 0x06 command when manually clicking?

**Comment by j3kestrel** [comment] 2018-02-19 01:02
I'm furiously packing and will be away for a week or so.  I will get the all-link data bases from the devices involved and get some logs after I return.   Most of my Insteon equipment is about 7 years old.

**Comment by TD22057** [comment] 2018-03-30 16:18
OK - let me know when you have time to grab those logs and I'll take a look.

**Comment by TD22057** [comment] 2018-07-07 16:47
Any chance you could take another look and grab those logs?  FYI - I just merged commits from @krkeegan to add more support for older devices. I don't think it will help w/ this but my guess is that the I1 devices are not behaving the same as the new devices for the scene off command.  With the update, we should know if a device is an older device now and with the logs I can probably add a special case to catch this.

**Comment by TD22057** [comment] 2019-01-25 01:01
Another ping on this - I'll probably close this as a won't fix in the next month or so unless I hear from you.

**Comment by TD22057** [comment] 2019-03-16 04:29
Per previous comment - I'm not able to reproduce this and without logs, there isn't anything I can do.  Feel free to re-open if you can upload the logs from this error.

**Closed by TD22057** 2019-03-16 04:29 UTC
